catalog: dbdemos_henryk
schema: titanic_mlops_dev
experiment_name: /Shared/titanic-mlops-dev
model_name: titanic_survival_model
endpoint_name: titanic-survival-endpoint-dev
test_size: 0.2
random_state: 42
hyperopt_max_evals: 10
min_accuracy: 0.70
min_precision: 0.65
min_recall: 0.60
min_f1_score: 0.65
min_roc_auc: 0.75
